version: "3"
services:
  belajar-ts:
    container_name: belajar-ts
    restart: unless-stopped
    volumes:
        - /usr/src/app/node_modules
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
